title = "Polska Szkoła w Burnley"
baseURL = "https://dwapir.github.io/strona-testowa/"
languageCode = "pl-Pl"
theme = "ananke"


DefaultContentLanguage = "pl"
SectionPagesMenu = "main"
Paginate = 3 # 
googleAnalytics = ""
enableRobotsTXT = true
canonifyURL = true

[markup.goldmark.renderer]
  unsafe = true


[languages]
  [languages.pl]
    title = "Polska Szkoła w Burnley"
    weight = 1
    contentDir = "content/pl" 
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "Polish School in Burnley"
    weight = 2
    contentDir = "content/en"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Maciej K"
  favicon = "/images/fryderyk_chopin_logo.png"
  site_logo = ""
  description = "Witamy w Polskiej Szkole Sobotniej w Burnley"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/polskaszkola.wburnley"
